import type { TradeExchange, TradeInstrument } from "@/lib/trade-instruments";

/** Known ticker → TradingView EXCHANGE:SYMBOL overrides (ETFs, aliases). */
const SYMBOL_OVERRIDES: Record<string, string> = {
  // US ETFs commonly listed on AMEX/ARCA on TradingView
  VOO: "AMEX:VOO",
  SPY: "AMEX:SPY",
  IVV: "AMEX:IVV",
  VTI: "AMEX:VTI",
  VEA: "AMEX:VEA",
  VWO: "AMEX:VWO",
  VT: "AMEX:VT",
  VXUS: "AMEX:VXUS",
  VIG: "AMEX:VIG",
  BND: "AMEX:BND",
  AGG: "AMEX:AGG",
  GLD: "AMEX:GLD",
  SLV: "AMEX:SLV",
  DIA: "AMEX:DIA",
  IWM: "AMEX:IWM",
  EEM: "AMEX:EEM",
  EFA: "AMEX:EFA",
  IEFA: "AMEX:IEFA",
  IEMG: "AMEX:IEMG",
  SCHD: "AMEX:SCHD",
  TLT: "NASDAQ:TLT",
  QQQ: "NASDAQ:QQQ",
  QYLD: "NASDAQ:QYLD",
  ARKK: "AMEX:ARKK",
  SMH: "AMEX:SMH",
  JEPI: "AMEX:JEPI",
  XLE: "AMEX:XLE",
  XLF: "AMEX:XLF",
  XLK: "AMEX:XLK",
  XLV: "AMEX:XLV",
  // Crypto
  BTCUSD: "BINANCE:BTCUSDT",
  ETHUSD: "BINANCE:ETHUSDT",
  SOLUSD: "BINANCE:SOLUSDT",
  XRPUSD: "BINANCE:XRPUSDT",
  BNBUSD: "BINANCE:BNBUSDT",
  ADAUSD: "BINANCE:ADAUSDT",
  DOGEUSD: "BINANCE:DOGEUSDT",
  AVAXUSD: "BINANCE:AVAXUSDT",
  DOTUSD: "BINANCE:DOTUSDT",
  LINKUSD: "BINANCE:LINKUSDT",
  MATICUSD: "BINANCE:MATICUSDT",
  LTCUSD: "BINANCE:LTCUSDT",
  TRXUSD: "BINANCE:TRXUSDT",
  BCHUSD: "BINANCE:BCHUSDT",
  XLMUSD: "BINANCE:XLMUSDT",
  ATOMUSD: "BINANCE:ATOMUSDT",
  UNIUSD: "BINANCE:UNIUSDT",
  NEARUSD: "BINANCE:NEARUSDT",
  APTUSD: "BINANCE:APTUSDT",
  ARBUSD: "BINANCE:ARBUSDT",
  OPUSD: "BINANCE:OPUSDT",
  FILUSD: "BINANCE:FILUSDT",
  ETCUSD: "BINANCE:ETCUSDT",
  SUIUSD: "BINANCE:SUIUSDT",
  ALGOUSD: "BINANCE:ALGOUSDT",
  AAVEUSD: "BINANCE:AAVEUSDT",
  PEPEUSD: "BINANCE:PEPEUSDT",
  SHIBUSD: "BINANCE:SHIBUSDT",
  // FX
  USDTRY: "FX:USDTRY",
  EURUSD: "FX:EURUSD",
  GBPUSD: "FX:GBPUSD",
  USDJPY: "FX:USDJPY",
  EURTRY: "FX:EURTRY",
  GBPTRY: "FX:GBPTRY",
  AUDUSD: "FX:AUDUSD",
  USDCAD: "FX:USDCAD",
  USDCHF: "FX:USDCHF",
  NZDUSD: "FX:NZDUSD",
  EURGBP: "FX:EURGBP",
  EURJPY: "FX:EURJPY",
  // Commodities
  XAUUSD: "FX:XAUUSD",
  XAGUSD: "FX:XAGUSD",
  USOIL: "TVC:USOIL",
  UKOIL: "TVC:UKOIL",
  NATGAS: "NYMEX:NG1!",
  COPPER: "COMEX:HG1!",
  PLATINUM: "TVC:PLATINUM",
  PALLADIUM: "TVC:PALLADIUM",
  WHEAT: "CBOT:ZW1!",
  CORN: "CBOT:ZC1!",
  SOYBEAN: "CBOT:ZS1!",
  COFFEE: "ICEUS:KC1!",
  SUGAR: "ICEUS:SB1!",
  COCOA: "ICEUS:CC1!",
  COTTON: "ICEUS:CT1!",
  HEATOIL: "NYMEX:HO1!",
  GASOLINE: "NYMEX:RB1!",
  RICE: "CBOT:ZR1!",
  ALUMINUM: "COMEX:ALI1!",
  XPTUSD: "TVC:PLATINUM",
  XPDUSD: "TVC:PALLADIUM",
  POLUSD: "BINANCE:POLUSDT",
  TONUSD: "BINANCE:TONUSDT",
  RENDERUSD: "BINANCE:RENDERUSDT",
  SEIUSD: "BINANCE:SEIUSDT",
  TIAUSD: "BINANCE:TIAUSDT",
  HBARUSD: "BINANCE:HBARUSDT",
};

/** Investor exchange → TradingView prefix */
const EXCHANGE_PREFIX: Record<TradeExchange, string> = {
  BIST: "BIST",
  MOEX: "MOEX",
  NASDAQ: "NASDAQ",
  NYSE: "NYSE",
  XETRA: "XETR",
  EPA: "EURONEXT",
  LSE: "LSE",
  CRYPTO: "BINANCE",
  FX: "FX",
  COMEX: "COMEX",
  OTHER: "NASDAQ",
};

/**
 * Map an Investor TradeInstrument to a TradingView Advanced Chart symbol.
 * Format: EXCHANGE:TICKER (e.g. BIST:THYAO, MOEX:SBER, NASDAQ:AAPL).
 */
export function toTradingViewSymbol(
  instrument: Pick<TradeInstrument, "symbol" | "exchange" | "type">
): string {
  const sym = instrument.symbol.toUpperCase();
  if (SYMBOL_OVERRIDES[sym]) return SYMBOL_OVERRIDES[sym];
  const prefix = EXCHANGE_PREFIX[instrument.exchange] ?? "NASDAQ";
  return `${prefix}:${sym}`;
}

export { SYMBOL_OVERRIDES, EXCHANGE_PREFIX };
